### ISSUE TITLE
Add a README file please!!

### ISSUE THREAD

**Issue by arf1372** [gholhak/Information_extraction#2]
How this code must be used?? What is the structure? Add a README and explain these pieces of information.

**Comment by arf1372** [comment]
Also, the wiki feature of GitHub is a nice place to document code.

**Comment by dmc1778** [comment]
I've modified the readme file. By the time, I'll complete it and believe it will be a good place to start using the repository for the other members of the group.

**Comment by arf1372** [comment]
There is no README file in the repo btw.

**Comment by dmc1778** [comment]
documentation/readme
