### ISSUE TITLE
Use proper .gitignore file

### ISSUE THREAD

**Issue by arf1372** [gholhak/Information_extraction#3]
Git has a nice feature to ignore unrelated or local/temporary files which must not be included in the repository named `.gitignore`. It's a good practice to use a proper `.gitignore` to avoid adding temporary and configuration files to a repo (like the `.idea` folder created by JetBrains IDEs or temporary test files)

Here is more information about this feature:
https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring
https://git-scm.com/docs/gitignore

**Comment by dmc1778** [comment]
The  `.gitignore` feature is added to the project.
